### PR TITLE
Create TRANSCEIVER_DOM_THRESHOLD table in state DB

### PR DESCRIPTION
**Pull request by mihirpat1**
#### Description
This PR is adding the required changes for creating a table for DOM threshold in state DB. Please refer to CMIS_and_C-CMIS_support_for_ZR.md document for field definitions for [TRANSCEIVER_DOM_THRESHOLD](https://github.com/sonic-net/SONiC/blob/master/doc/platform_api/CMIS_and_C-CMIS_support_for_ZR.md#213-transceiver-dom-threshold-table).
Overall, TRANSCEIVER_DOM_SENSOR DB table currently comprised of fields for TRANSCEIVER_DOM_SENSOR as well as TRANSCEIVER_DOM_THRESHOLD. With the current PR, a separate entry in state DB has now been created for TRANSCEIVER_DOM_THRESHOLD related fields.
The new command to display the threshold relevant fields will be done separately and is currently being tracked using https://github.com/sonic-net/sonic-buildimage/issues/12911.

PR https://github.com/sonic-net/sonic-utilities/pull/2535 has now been created to ensure that the output from "show interface transceiver eeprom \<port\> -d" remains unchanged after the current PR is merged. Both the current PR and https://github.com/sonic-net/sonic-utilities/pull/2535 needs to be merged at the same time to avoid running into issues since they are dependent.

#### How Has This Been Tested?

400ZR related testing
[Unit-test_400ZR.txt](https://github.com/sonic-net/sonic-platform-daemons/files/10139365/Unit-test_400ZR.txt)

100G and 10G related testing
[Unit-test_100G_10G.txt](https://github.com/sonic-net/sonic-platform-daemons/files/10139362/Unit-test_100G_10G.txt)

Transceiver info o/p
[Unit-test_transceiver_info.txt](https://github.com/sonic-net/sonic-platform-daemons/files/10135442/Unit-test_transceiver_info.txt)

400ZR UT for multi-asic switch
[Unit-test_400ZR_Multiasic.txt](https://github.com/sonic-net/sonic-platform-daemons/files/10157449/Unit-test_400ZR_Multiasic.txt)

#### Additional Information (Optional)

Signed-off-by: Mihir Patel <patelmi@microsoft.com>

### CODE REVIEW

**Comment by shyam77git** [comment]
@mihirpat1 
Looked into the UT logs.
Don't see output/display for 'show int transceiver eeprom' CLIs with this change.
Could you add them?

**Comment by mihirpat1** [comment]
> @mihirpat1 Looked into the UT logs. Don't see output/display for 'show int transceiver eeprom' CLIs with this change. Could you add them?

The current PR is only for supporting the state DB related changes. I have filed https://github.com/sonic-net/sonic-buildimage/issues/12911 to track the CLI support for the same.

**Comment by jaganbal-a** [comment]
I see the o/p of "sfpshow eeprom -d -p port_name" have "ModuleThresholdValues:" and looks incomplete. 
Do you want to keep the CLI o/p this way until https://github.com/sonic-net/sonic-buildimage/issues/12911 fix commit?
   ModuleMonitorValues:
	                Temperature: 73.91C
	                Vcc: 3.347Volts
	        ModuleThresholdValues:
	
	root@sonic:/home/admin#

**Comment by mihirpat1** [comment]
> I see the o/p of "sfpshow eeprom -d -p port_name" have "ModuleThresholdValues:" and looks incomplete. Do you want to keep the CLI o/p this way until [sonic-net/sonic-buildimage#12911](https://github.com/sonic-net/sonic-buildimage/issues/12911) fix commit? ModuleMonitorValues: Temperature: 73.91C Vcc: 3.347Volts ModuleThresholdValues:
> 
> ```
> root@sonic:/home/admin# 
> ```

Yes, the corresponding changes will be done with the issue mentioned above

**Comment by jaganbal-a** [comment]
> > I see the o/p of "sfpshow eeprom -d -p port_name" have "ModuleThresholdValues:" and looks incomplete. Do you want to keep the CLI o/p this way until [sonic-net/sonic-buildimage#12911](https://github.com/sonic-net/sonic-buildimage/issues/12911) fix commit? ModuleMonitorValues: Temperature: 73.91C Vcc: 3.347Volts ModuleThresholdValues:
> > ```
> > root@sonic:/home/admin# 
> > ```
> 
> Yes, the corresponding changes will be done with the issue mentioned above

the show int trans CLI o/p will have the Module threshold values right? 
otherwise it will be difficult to debug any signal out of range scenario.

**Comment by mihirpat1** [comment]
> > > I see the o/p of "sfpshow eeprom -d -p port_name" have "ModuleThresholdValues:" and looks incomplete. Do you want to keep the CLI o/p this way until [sonic-net/sonic-buildimage#12911](https://github.com/sonic-net/sonic-buildimage/issues/12911) fix commit? ModuleMonitorValues: Temperature: 73.91C Vcc: 3.347Volts ModuleThresholdValues:
> > > ```
> > > root@sonic:/home/admin# 
> > > ```
> > 
> > 
> > Yes, the corresponding changes will be done with the issue mentioned above
> 
> the show int trans CLI o/p will have the Module threshold values right? otherwise it will be difficult to debug any signal out of range scenario.

Need access since part of SONiC teamI have now raised https://github.com/sonic-net/sonic-utilities/pull/2535 to ensure that the CLI output remains unchanged with the current changes. We plan to commit both this and https://github.com/sonic-net/sonic-utilities/pull/2535 at the same time to avoid running into dependency issues.

**Review by shyam77git — APPROVED** [review]
LGTM

**Review by jaganbal-a — APPROVED** [review]

**Comment by mihirpat1** [comment]
> @mihirpat1 Have added comment to PR [sonic-net/sonic-utilities#2535](https://github.com/sonic-net/sonic-utilities/pull/2535). Please take care of it. Approving this one

I have added the requested UT enclosure to this PR now.

**Review by prgeor — APPROVED** [review]

**Pull request merged**
