### PR TITLE
Support to get MEDIA_SETTING and OPTICS_SI from both platform folder and HWSKU folder

### PR DESCRIPTION
**Pull request by keboliu**
#### Description
Support to get the media_settings.json and optics_si_settings.json files from both the platform folder and the SKU folder.
It will search the HWSKU folder first and then fall back to the platform folder.

combine with PR https://github.com/sonic-net/sonic-buildimage/pull/18441, the vendor will be able to enable CMIS cable host mgmt. function per SKU(choose to put the specific pmon_daemon_control.json, media_settings.json and optics_si_settings.json to the SKU folder).

#### Motivation and Context
The vendor will have the flexibility to have both files in the platform scope or the SKU scope.

#### How Has This Been Tested?

Build image, manually test,
1. put files in the platform folder, the settings should be able to be loaded.
2. put files in the SKU folder, the settings should be able to be loaded.
3. put the files in both platform and SKU folder, the settings in the SKU folder will be loaded.

### CODE REVIEW

**Comment by prgeor** [comment]
@keboliu Pleas specify the other dependent PR in the description.

**Review by Junchao-Mellanox — APPROVED** [review]

**Comment by keboliu** [comment]
> @keboliu Pleas specify the other dependent PR in the description.

done.

**Review by mihirpat1 — APPROVED** [review]

**Review by prgeor — DISMISSED** [review]

**Comment by prgeor** [comment]
@keboliu please fix the build failure

**Comment by keboliu** [comment]
> @keboliu please fix the build failure

fixed, would you please approve again?

**Comment by keboliu** [comment]
@prgeor would you please review and merge?

**Comment by liat-grozovik** [comment]
@prgeor can we go a head and merge?

**Review by prgeor — APPROVED** [review]

**Comment by prgeor** [comment]
@liat-grozovik @keboliu there is cherry pick conflict for 202311. please raise separate PR for 202311

**Comment by keboliu** [comment]
> [202311] Support to get MEDIA_SETTING and OPTICS_SI from both platform folder and HWSKU folder
@prgeor done, https://github.com/sonic-net/sonic-platform-daemons/pull/460

**Pull request merged**
