### PR TITLE
[xcvrd] Fix issue: logical_port_name is not defined

### PR DESCRIPTION
**Pull request by Junchao-Mellanox**
#### Description

Fix issue: logical_port_name is not defined

#### Motivation and Context

Fix issue: logical_port_name is not defined

#### How Has This Been Tested?

Manual test

### CODE REVIEW

**Review by keboliu — APPROVED** [review]

**Review by prgeor — DISMISSED** [review]

**Comment by prgeor** [comment]
@Junchao-Mellanox build is failing...

**Review by mihirpat1 — APPROVED** [review]

**Comment by mihirpat1** [comment]
@Junchao-Mellanox Please help in fixing the code coverage check

**Comment by Junchao-Mellanox** [comment]
Hi @prgeor , UT added, could you please review?

**Review by prgeor — APPROVED** [review]

**Comment by yxieca** [comment]
@Junchao-Mellanox @prgeor I don't have enough information from PR comment to understand the change and issue it is addressing. Please update the PR comments with more information. @prgeor  do you agree to backport this change?

**Comment by Junchao-Mellanox** [comment]
Hi @yxieca , I added some description. Please kindly review again.

**Pull request merged**
