### PR TITLE
[ycabled][build] Fix sonic_ycabled build failure in Bookworm

### PR DESCRIPTION
**Pull request by ArunSaravananBalachandran**
#### Description

Use 'build_py' command to include the gRPC libraries in the package while building with 'python3 -m build' 

#### Motivation and Context

In Bookworm, `python3 -m build -n` is used to build python wheel packages inplace of `python3 setup.py bdist_wheel`.
(Ref: https://github.com/sonic-net/sonic-buildimage/commit/9dfa546e07e13861338205ee79944b17df2c6cce)

When 'python3 -m build -n' is executed, by default 'sdist' command is executed and it copies .py and other default files to separate dir and generates a sdist of it, from which a wheel is created. 
Since 'sdist' does not copy .proto files, the gRPC libraries are not generated while building the wheel from the sdist.

To resolve the above issue, the gRPC libraries are generated in 'build_py' initialization to ensure that they are available for 'sdist' and other commands during the build.

#### How Has This Been Tested?

Build sonic_y_cabled in Python3.11 with `python3 -m build -n` command and verify that the gRPC libraries are available in the generated wheel package.

build log before fix: [sonic_ycabled_build_logs_before_fix.txt](https://github.com/sonic-net/sonic-platform-daemons/files/14220186/sonic_ycabled_build_logs_before_fix.txt)

build log with fix: [sonic_ycabled_build_logs_with_fix.txt](https://github.com/sonic-net/sonic-platform-daemons/files/14220187/sonic_ycabled_build_logs_with_fix.txt)

### CODE REVIEW

**Comment by prgeor** [comment]
@vdahiya12 can you review?

**Review by vdahiya12 — APPROVED** [review]

**Review by saiarcot895 — APPROVED** [review]
I attempted to use a different approach in #441, where the proto files are packaged into the tarball, and then the python bindings are generated as part of `build_py`. However, that breaks the CI pipeline because it runs the test first, which only runs `build_ext`.

This could maybe be improved in the future, but for current requirements, this is fine.

**Comment by vivekrnv** [comment]
Hi,

Tests are failing. Can you check?

```
=========================== short test summary info ============================
FAILED tests/test_y_cable_helper.py::TestYCableScript::test_check_identifier_presence_and_update_mux_table_entry_module_none - AttributeError: 'dict' object attribute 'get' is read-only
FAILED tests/test_y_cable_helper.py::TestYCableScript::test_check_identifier_presence_and_update_mux_table_entry_module_microsoft - AttributeError: 'dict' object attribute 'get' is read-only
FAILED tests/test_y_cable_helper.py::TestYCableScript::test_check_identifier_presence_and_update_mux_table_entry_module_microsoft_y_cable_presence_false - AttributeError: 'dict' object attribute 'get' is read-only
================== 3 failed, 267 passed, 67 warnings in 8.58s ==================
[  FAIL LOG END  ] [ target/python-wheels/bookworm/sonic_ycabled-1.0-py3-none-any.whl ]
```

**Comment by ArunSaravananBalachandran** [comment]
> Hi,
> 
> Tests are failing. Can you check?
> 
> ```
> =========================== short test summary info ============================
> FAILED tests/test_y_cable_helper.py::TestYCableScript::test_check_identifier_presence_and_update_mux_table_entry_module_none - AttributeError: 'dict' object attribute 'get' is read-only
> FAILED tests/test_y_cable_helper.py::TestYCableScript::test_check_identifier_presence_and_update_mux_table_entry_module_microsoft - AttributeError: 'dict' object attribute 'get' is read-only
> FAILED tests/test_y_cable_helper.py::TestYCableScript::test_check_identifier_presence_and_update_mux_table_entry_module_microsoft_y_cable_presence_false - AttributeError: 'dict' object attribute 'get' is read-only
> ================== 3 failed, 267 passed, 67 warnings in 8.58s ==================
> [  FAIL LOG END  ] [ target/python-wheels/bookworm/sonic_ycabled-1.0-py3-none-any.whl ]
> ```

https://github.com/sonic-net/sonic-platform-daemons/pull/431 was raised to fix the unittest issue. 
Could you please let me know if the above fix is in place while running the tests ?

**Review by vivekrnv — APPROVED** [review]

**Review by prgeor — APPROVED** [review]

**Comment by ArunSaravananBalachandran** [comment]
> @ArunSaravananBalachandran can you rebase?

The branch has been rebased.

**Pull request merged**
