### PR TITLE
[xcvrd] Use new logger implementation and enable runtime log level configuration

### PR DESCRIPTION
**Pull request by Junchao-Mellanox**
Depends on https://github.com/sonic-net/sonic-buildimage/pull/19611

#### Description

Use new logger class `SysLogger` and enable runtime log level configuration

#### Motivation and Context

Use new logger class `SysLogger` and enable runtime log level configuration

#### How Has This Been Tested?

Manual test

### CODE REVIEW

**Comment by Junchao-Mellanox** [comment]
The checker failure is expected. It should pass after https://github.com/sonic-net/sonic-buildimage/pull/19611 merged.

**Comment by prgeor** [comment]
@Junchao-Mellanox is this PR ready for review? I see in draft mode

**Review by keboliu — DISMISSED** [review]

**Comment by Junchao-Mellanox** [comment]
The UT failure is caused by dependency miss. The dependency https://github.com/sonic-net/sonic-buildimage/pull/19611 was merged on 10-27.
But there is no vs.master build since 10-25: https://sonic-build.azurewebsites.net/ui/sonic/pipelines/142/builds?branchName=master.

**Review by keboliu — APPROVED** [review]

**Pull request merged**
